# CPSR configuration options (TOML).

[secondary_findings]
## Include variants found in ACMG-recommended list for incidental findings
## https://www.ncbi.nlm.nih.gov/clinvar/docs/acmg/
show_sf = true

[maf_limits]
## choose upper MAF threshold (global) for variants to be included in report
maf_gnomad = 0.9

[popgen]
## choose population source in gnomAD, defaults to the global set
## For gnomAD, this can by any of the following values (three-letter codes):
## "afr" - African/American
## "amr" - Admixed American
## "eas" - East Asian
## "sas" - Sout Asian
## "asj" - Ashkenazi Jewish
## "nfe" - Non-Finnish European
## "fin" - Finnish
## "global" - All populations combined
pop_gnomad = "nfe"

[visual]
# Choose visual theme of report, any of: "default", "cerulean", "journal", "flatly", "readable", "spacelab", "united", "cosmo", "lumen", "paper", "sandstone", "simplex", or "yeti" (https://bootswatch.com/)
report_theme = "default"

[custom_tags]
## list VCF info tags that should be present in JSON output
## tags should be comma separated, i.e. custom_tags = "GATK_FILTER,VARSCAN_FILTER"
custom_tags = ""

[custom_panel]
## edit metadata (name, version, url) of relevance for custom-provided gene panel (provided by option --custom_panel)
name = "Custom gene panel"
version = "1.0"
url = ""

[classification]
## for variants with an existing classification in ClinVar, include CPSR classification/score in the output TSV file
clinvar_cpsr = true

[gwas]
gwas_hits = true
## Required p-value for reporting of GWAS hits
p_value_min = 5e-6

[other]
n_vcfanno_proc = 4
n_vep_forks = 4
vep_skip_intergenic = false
vep_pick_order = "canonical,appris,tsl,biotype,ccds,rank,length,mane"
